// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEEZ4l1_lPqv-J-3WBArf3cJ0XWMBQRzs',
    appId: '1:204129505658:web:c596ef1b4ea4ccd3aec6c3',
    messagingSenderId: '204129505658',
    projectId: 'test-project01-393a7',
    authDomain: 'test-project01-393a7.firebaseapp.com',
    storageBucket: 'test-project01-393a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCv4NseaH9K1pDAah6WRsUOJkzbyhtBq0',
    appId: '1:204129505658:android:d49622109cb1d0b8aec6c3',
    messagingSenderId: '204129505658',
    projectId: 'test-project01-393a7',
    storageBucket: 'test-project01-393a7.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEEZ4l1_lPqv-J-3WBArf3cJ0XWMBQRzs',
    appId: '1:204129505658:web:9a9005f02c038a0daec6c3',
    messagingSenderId: '204129505658',
    projectId: 'test-project01-393a7',
    authDomain: 'test-project01-393a7.firebaseapp.com',
    storageBucket: 'test-project01-393a7.appspot.com',
  );
}
